import SideBar from "@/components/shared/SideBar";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const Dashboardlayout = ({ children }) => {
    return (
        <div className="flex">
            <SideBar></SideBar>
            <div className="w-full">{children}</div>
        </div>
    );
};

export default Dashboardlayout;